### ISSUE TITLE
Why second to last layer Vision Transformer features?

### ISSUE THREAD

**Issue by gorjanradevski** [TRI-ML/prismatic-vlms#22]
Hello, I've seen that in the codebase you're obtaining the second-to-last layer patch features from the ViT: [`L123 in base_vision.py`](https://github.com/TRI-ML/prismatic-vlms/blob/main/prismatic/models/backbones/vision/base_vision.py#L123). What is the reason for doing that and would you expect lower performance if you simply `forward_features()` from the model?

**Comment by siddk** [comment]
Hey @gorjanradevski -- so this was a decision we primarily made in order to replicate the original LLaVa (and LLaVa-v1.5) models -- as mentioned in their paper they see a slight lift using second-to-last-layer features.

We confirmed there's a (very small gain) in using these vs. last-layer features in early experiments so we kept it for all our experiments. That being said, it was maybe a 1-2% difference on the VQA evaluations -- I don't think there's a problem using `forward_features()` directly.
